### ISSUE TITLE
Support ansible-galaxy install

### ISSUE THREAD

**Issue by donovanmuller** [radekg/terraform-provisioner-ansible#133]
It would be great to add support for `ansible-galaxy install` before running plays.
Especially in the form of a [`requirements.yml`](https://galaxy.ansible.com/docs/using/installing.html#installing-multiple-roles-from-a-file)
E.g.

```terraform
...
  provisioner "ansible" {
    plays {
      galaxy {
         requirements = [
            file_path = "${path.module}/ansible/requirements.yml"
         ]
      }
      playbook {
        file_path = "${path.module}/ansible/playbooks/example.yml"
        roles_path = [
          "${path.module}/ansible/roles"
        ]
      }
    }
...
```

or something like that...

**Comment by radekg** [comment]
This looks like a good candidate to implement. Should not be very difficult to add.
