### ISSUE TITLE
Generate schema for use in editors such as Jetbrains IntelliJ

### ISSUE THREAD

**Issue by benosman** [radekg/terraform-provisioner-ansible#134]
I use IntelliJ IDEA along with the HCL plugin to edit terraform files.

It's helpful to have full syntax support for this ansible provisioner, especially as there is a plethora of options available. Other editors support these kind of files, which should be placed in the `~/.terraform.d/schemas` directory.

Now terraform 0.12 contains a command (`terraform providers schema`) to generate schema for installed providers, but it does not include provisioners. 

I found a [gist](https://gist.github.com/ArthurHlt/45d4207c557dd614735a4aabc3d12976) for a golang file that creates a schema for a provider, so I adjusted it to make it work for ansible-provisioner.

I had trouble simply creating a generic tool for provisioners, as since the resource_provisioner file is in the root of the directory tree it is not importable.

So, after moving that into the ansible subfolder, I managed to get it working. Here is the resultant schema and the code I used:
https://gist.github.com/benosman/1c7c6826ec45dfc8292f090056d63ef4

It would be cool if you could find a way to incorporate the generation of the schema into your build process so it gets automatically generated and placed into the repo in order to reflect any future changes to the schema.

**Comment by radekg** [comment]
Thank you for the tip. I'll have a look at it.

**Comment by bizmate** [comment]
it might not be related but i am getting error 
```
Error: Failed to instantiate provisioner "ansible" to obtain schema: unknown provisioner "ansible"
```
Is this related or your request is just an enhancement for intelliJ?
