### ISSUE TITLE
Ansible run  approach Q

### ISSUE THREAD

**Issue by vmindru** [radekg/terraform-provisioner-ansible#14]
Hi, i was wondering why did you decide to install ansible on the target host insted of running it locally against the target server? 

https://github.com/radekg/terraform-provisioner-ansible/blob/db094ae4742f037a5b482f737fcd0867a4971545/provisioner.go#L249

**Comment by radekg** [comment]
Hey @vmindru, I've been planning that when I finally get out of #12.
I've created https://github.com/radekg/terraform-provisioner-ansible/issues/15 to track progress on that.
Going to close this one.
