### ISSUE TITLE
error on terraform v0.12.14 

### ISSUE THREAD

**Issue by terryzwt** [radekg/terraform-provisioner-ansible#144]
**Terraform version**: 0.12.14

**terraform-provisioner-ansible version/SHA**:

**Terraform file / provisioner configuration**:

```
https://github.com/terryzwt/alicloud-ikev2-server/blob/master/main.tf#L95
```

**Terraform run log:**

```

Error: Unsupported argument

  on main.tf line 94, in resource "alicloud_instance" "instance":
  94:       playbook = {

An argument named "playbook" is not expected here. Did you mean to define a
block of type "playbook"?
```

**Comment by terryzwt** [comment]
When I degrade terraform to v0.11.14, there is no error.

Thanks for checking.

**Comment by radekg** [comment]
Hi @terryzwt. For Terraform 0.12.x, please try:

```
playbook {
```

Without `=`. Please have a look at the relevant readme: https://github.com/radekg/terraform-provisioner-ansible#configuration.

**Comment by terryzwt** [comment]
Hi @radekg ,thanks for your quick help . it works now!
