### ISSUE TITLE
Terraform-provisioner-ansible cannot be found at registry.terraform.io

### ISSUE THREAD

**Issue by nathaclmpaulino** [radekg/terraform-provisioner-ansible#147]
Hello,

Is there a reason why terraform-provisioner-ansible cannot be found at registry.terraform.io? 

 **Actual Behaivor** 
When i run `terraform init` on a folder with this snippet below, i get this error

Snippet:
`module "ansible" {
  source  = "radekg/ansible/provisioner"
  version = "2.3.0"
}`

Error:
`Module "ansible" cannot be found in the module registry at registry.terraform.io.`

In my folder `~/.terraform.d/plugins` i have terraform-provisioner-ansible_v2.3.0.

**Comment by radekg** [comment]
Hi @NathaPaulino. Unfortunately, provisioners are not supported to the same extent as providers. Here is the relevant feature request for terraform: https://github.com/hashicorp/terraform/issues/19477.

The installation process is documented here: https://github.com/radekg/terraform-provisioner-ansible#local-installation.
