### ISSUE TITLE
deploy-release.sh script fails on curl call

### ISSUE THREAD

**Issue by mtin** [radekg/terraform-provisioner-ansible#159]
### Steps to reproduce

use installation method as described in the README:

```
curl -sL \
  https://raw.githubusercontent.com/radekg/terraform-provisioner-ansible/master/bin/deploy-release.sh \
  --output /tmp/deploy-release.sh
chmod +x /tmp/deploy-release.sh
/tmp/deploy-release.sh -v 2.4.0
rm -rf /tmp/deploy-release.sh
```

### Expected behavior

...installation happens

### Actual behavior

the curl call checking the version (line 60 in deploy-release.sh) fails, the reply does not contain a 'status' field as far as I can tell

**Comment by radekg** [comment]
Thank you for reporting. This has been addressed https://github.com/radekg/terraform-provisioner-ansible/pull/161.
