### ISSUE TITLE
Change hosts to a structure

### ISSUE THREAD

**Issue by radekg** [radekg/terraform-provisioner-ansible#22]
Instead of taking `[]string{ ... }`, take a set of `hosts`. This will allow for:

```
host {
  name = "..."
  ansible_connection = "..."
  ansible_port = ...
  ansible_user = ...
}
```

This change will eliminate double template. `ansible_port` can be read from `connInfo.Port`.

**Comment by slapula** [comment]
@radekg mind if I take a stab at this?  I've been looking to add something like this to my Hacktoberfest to-do list.

**Comment by radekg** [comment]
Hi @slapula, normally I would say „go for it”. However, in this case, there is work in progress on version 2.0, which will include this feature.

As the 2.0 preview is likely to be available within days, I’d suggest not going for this right now.

Hope this sounds reasonsble. Thanks for offering the help!

**Comment by radekg** [comment]
After spending some time on this issue while working on version 2.0.0, it appears that this functionality is not required. In fact, implementing this might make the tool much more difficult to use and reason about.

#### Local provisioning

The intent is to execute Ansible against a resource provisoned with Terraform. This implies that a single Ansible run is executed for each `play`, for each machine created using a resource. All connection details: type (at this moment `ssh` only, username, private key, bastion host details, port), are all inherited from the resource's `connection`. The only time when having the ability to set a host for a local run makes sense, is to be able to provide an alias for the inventory construct of the following form:

    [group]
    alias ansible_host=...

All other settings like: `ansible_user`, `ansible_port`, `ansible_host`, are delivered to the Ansible command while constructing the Ansible command to be executed.

The intent is not to create another arbitrary way of running Ansible commands. For such complex scenarios, it might be better to use a local exec provisioner and construct the required Ansible command by hand.

#### Remote provisoner

Similar to the local provisoner, the intent is to execute Ansible for the provisioned resources. The major difference is to run Ansible on the provisioned resource instead of the local one. The only required option for remote provisioner, at this moment in time, is the `ansible_connection=local`.

#### Summary

In both cases, changing the `hosts` from `[]string` to a list of `Host` provides so many new options to handle that the complexity of managing the feature becomes a burden. For example, handling passwords, usernames, keys.

It is possible that this change would be, indeed, beneficial. However, the change needs to be implemented based on a real need, rather than only because it can be done. The side-effects of making the change must be well thought out and planned for.

As such, at this moment in time, this feature will not be implemented. Once the need appears and the reasoning and impact is clear, the feature will be considered.
