### ISSUE TITLE
Change groups to a list

### ISSUE THREAD

**Issue by radekg** [radekg/terraform-provisioner-ansible#23]
Instead of taking a `[]string{ ... }`, take a list of `groups`. The functionality will be:

```
group {
  name = "..."
  inherit_hosts = true
}

group {
  name = "..."
  host {
    ...
  }
}
```

It must be possible to combine `inherit_hosts` with additional `hosts` and have an empty group which does not inherit, neither provides additional hosts.

**Comment by JamesUoM** [comment]
Need to be able to specify group hierarchy too. As it appears groups_vars are applied in alphabetical order by ansible when the groups are at the same depth: https://github.com/ansible/ansible/commit/a83b00bbc0d77a5f56e317bcb88766e4e9c999db

this leads to weird results when trying to override base group variables

**Comment by radekg** [comment]
As with https://github.com/radekg/terraform-provisioner-ansible/issues/22, the complexity of having this feature in without a proper impact analysis does not make it a good candidate for implementation just for the sake of having it done.

I'm closing this issue until there is a real world need for having this in.
