### ISSUE TITLE
How can I change inventory_hostname?

### ISSUE THREAD

**Issue by jakubgs** [radekg/terraform-provisioner-ansible#46]
I know I can set `inventory_hostname` in `extra_vars`, but it does not affect the key under which the host metadata exists in the inventory, it's still under an IP. How can I change it so instead of IP it uses my given DNS entry?

**Comment by jakubgs** [comment]
I might add why I want this. I set the hostname based on `inventory_hostname`, but if I change `inventory_hostname` in `extra_vars` then something like:
```
hostvars[inventory_hostname].data_center 
```
Fails because the key I need is the IP, not the hostname.

**Comment by radekg** [comment]
I'll investigate and come back to you. Thanks for report.

**Comment by radekg** [comment]
This will be fully functional in an upcoming 2.0.0 release:

- https://github.com/radekg/terraform-provisioner-ansible/commit/b6885c14bff983e7bc287baa90c4b543f2e262b8

**Comment by jakubgs** [comment]
Thanks a bunch for this man! I owe you a beer if we ever meet.
