### ISSUE TITLE
plays.hosts needs documenting

### ISSUE THREAD

**Issue by JamesUoM** [radekg/terraform-provisioner-ansible#47]
The plays.hosts argument is not documented. It is unclear how this interacts with the hosts provisioner argument and why the latter is ignored in local mode.

**Comment by radekg** [comment]
This has been documented in the readme for an upcoming 2.0.0 release: https://github.com/radekg/terraform-provisioner-ansible/commit/6473822b7d20e5a50f81efe30faa0cb26b3f05d2
