### ISSUE TITLE
Roles not uploaded with playbook

### ISSUE THREAD

**Issue by taylorsmithgg** [radekg/terraform-provisioner-ansible#49]
My current ansible repo has the structure:
├── inventories
│   ├── directory
├── playbooks
│   ├── directory
├── roles
│   ├── directory

Upon copying the playbook I want to run, the roles are not copied.

**Comment by taylorsmithgg** [comment]
Perhaps we could allow specifying a `roles_dir` or something similar?

The current requirements appear to force nesting roles under the playbook's directory

**Comment by radekg** [comment]
Hey @taylorsmithgg, is this in local or remote mode?

**Comment by taylorsmithgg** [comment]
Remote, I originally tried local, referenced here #50

**Comment by taylorsmithgg** [comment]
``` provisioner "ansible" {
    connection {
      type = "ssh"
      host = "${self.private_ip}"
      user = "ec2-user"
      bastion_host = "${var.bastion}"
      bastion_user = "${var.user}"
    }

    plays {
      playbook = "${var.ansible_path}/playbooks/application/server.yaml"
    }

    local  = "no"
    verbose = "yes"
    use_sudo = "yes"
    skip_install = "no"
    skip_cleanup = "yes"
  }```

**Comment by radekg** [comment]
Thank you, what about the #50 ? You’ve mentioned it did not respect local ssh config settings?

**Comment by radekg** [comment]
This will be functional in an upcoming 2.0.0 release:

- https://github.com/radekg/terraform-provisioner-ansible/commit/981d3a1ea0d73b59a471396eba447447e0381796
- https://github.com/radekg/terraform-provisioner-ansible/commit/0b0ed473c8c1c49b13e5db0cf82d87ce9d3d5b50
