### ISSUE TITLE
make build-linux fails with Go 1.6

### ISSUE THREAD

**Issue by giuliov** [radekg/terraform-provisioner-ansible#52]
This does not compile with the golang-1.6 package in the Ubuntu 16.04 release:
```
mkdir -p ~/.terraform.d/plugins
CGO_ENABLED=0 GOOS=linux installsuffix=cgo go build -o ./terraform-provisioner-ansible-linux
provisioner.go:6:2: cannot find package "context" in any of:
        /home/user/go/src/github.com/radekg/terraform-provisioner-ansible/vendor/context (vendor tree)
        /usr/lib/go-1.6/src/context (from $GOROOT)
        /home/user/go/src/context (from $GOPATH)
Makefile:22: recipe for target 'build-linux' failed
make: *** [build-linux] Error 1
```
I had installed `go1.6.2 linux/amd64` on Ubuntu 16.04.4 LTS running on Windows 10 v.1709
Now, I installed manually golang 1.10 and it works.

**Comment by chokhareganesh** [comment]
set $GOPATH if fails,[run gave commands](https://stackoverflow.com/questions/21001387/how-do-i-set-the-gopath-environment-variable-on-ubuntu-what-file-must-i-edit) and do further steps for ansible  provisioner

**Comment by giuliov** [comment]
I meant that the build script does not check for the go version and the one installed via apt is too old. The build script should check for a minimal version of the go compiler.
