### ISSUE TITLE
Can't build application "exit status 128". Request for pre-built artifacts.

### ISSUE THREAD

**Issue by Bluesboy** [radekg/terraform-provisioner-ansible#55]
After running `make install` build always fail with:
```[ERROR] Export failed for github.com/hashicorp/terraform: Unable to export source: exit status 128```
and sometimes same error with other packages like `google.golang.org/genproto` etc.
I'm not "go person" and for people like me it would be cool to just download package from *releases* and be happy. Hope it is possible.

**Comment by radekg** [comment]
Hi @Bluesboy, thanks for the suggestion regarding prebuilt binaries. These will now be available via [GitHub releases](https://github.com/radekg/terraform-provisioner-ansible/releases) and [Terraform Module Registry](https://registry.terraform.io/modules/radekg/ansible/provisioner).

Hope this helps.
