### ISSUE TITLE
Unreachable; "argument must be an int"

### ISSUE THREAD

**Issue by DanielMarquard** [radekg/terraform-provisioner-ansible#98]
### Steps to reproduce

Use the local Ansible provisioner, with or without `insecure_no_strict_host_key_checking`.

### Expected behavior

Ansible authenticates via SSH.

### Actual behavior

Hosts are "unreachable", but this is not the case for the Ansible remote provisioner.

### Configuration

**Terraform version**: latest stable release

**terraform-provisioner-ansible version/SHA**: latest release

**Terraform run log:**

```
TASK [Gathering Facts] *********************************************************
fatal: [IP redacted]: UNREACHABLE! => {"changed": false, "msg": "argument must be an int, or have a fileno() method", "unreachable": true}
```

**Comment by DanielMarquard** [comment]
We needed a `host_key_checking = False` config option for some reason. `StrictHostKeyChecking=no` wasn't enough.

**Comment by radekg** [comment]
Hi @DanielMarquard. Thank you for the report.

The solution with `host_key_checking = False` worked for you? This could be a documentation issue.

**Comment by DanielMarquard** [comment]
Yep, that worked after we pushed an ansible.cfg.

On Nov 24, 2018, at 9:45 AM, Rad Gruchalski <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @DanielMarquard<https://github.com/DanielMarquard>. Thank you for the report.

The solution with host_key_checking = False worked for you? This could be a documentation issue.

**Comment by radekg** [comment]
Thank you for the update. I will close this issue for the moment as it appears to have a solution. However, I will get back to this when the time for #10 comes.
